/**
 * Utility to generate a simple parametric OpenSCAD script for a
 * flower‑shaped rainwater collector that can be mounted on a tinaco.
 *
 * The model consists of:
 *  - A central cylindrical hub (the mount point)
 *  - A configurable number of petals created by rotating a 2‑D profile
 *    around the hub.
 *
 * The function returns the raw OpenSCAD source as a string, which can be
 * saved to a `.scad` file or rendered on the client side.
 */

export interface FlowerCollectorParams {
  /** Diameter of the central hub (mm) */
  hubDiameter?: number;
  /** Height of the central hub (mm) */
  hubHeight?: number;
  /** Number of petals (minimum 3) */
  petalCount?: number;
  /** Length of each petal from hub edge (mm) */
  petalLength?: number;
  /** Width of each petal at its base (mm) */
  petalBaseWidth?: number;
  /** Thickness of the collector walls (mm) */
  wallThickness?: number;
}

/**
 * Generates an OpenSCAD script for the flower‑shaped collector.
 *
 * @param params - Optional parameters to customise the shape.
 * @returns OpenSCAD source code.
 */
export function generateFlowerCollector(params: FlowerCollectorParams = {}): string {
  const {
    hubDiameter = 200,
    hubHeight = 150,
    petalCount = 8,
    petalLength = 300,
    petalBaseWidth = 120,
    wallThickness = 5,
  } = params;

  // Basic validation
  if (petalCount < 3) {
    throw new Error('petalCount must be at least 3');
  }

  // Helper to create a single petal using a 2‑D polygon extruded to thickness
  const petal2D = `
module petal2d() {
  polygon(points=[
    [0,0],
    [${petalBaseWidth / 2},${wallThickness}],
    [${petalLength - wallThickness},${petalLength * 0.6}],
    [${petalLength},${petalLength}]
  ]);
}
`;

  // Full OpenSCAD script
  const script = `
// Flower‑shaped rainwater collector
// Generated by generateFlowerCollector()

${petal2D}

// Central hub (mount point)
module hub() {
  cylinder(d=${hubDiameter}, h=${hubHeight}, $fn=64);
}

// One petal (extruded to wall thickness)
module petal() {
  linear_extrude(height=${wallThickness}) petal2d();
}

// Assemble the collector
module collector() {
  hub();
  // Rotate and position petals around the hub
  for (i = [0:${petalCount - 1}]) {
    rotate([0,0,i*360/${petalCount}])
      translate([${hubDiameter / 2},0,${hubHeight - wallThickness}])
        petal();
  }
}

// Render the collector
collector();
`;

  return script.trim();
}
