[package]
name = "competition-metric-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["serde/std", "serde_json/std"]

[dependencies]
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
tiny-keccak = { version = "2", features = ["keccak"] }

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true
