
// This test suite focuses on simulating an end-to-end flow for a "direct profitable inventory contract".
// It defines a minimal contract model to demonstrate the core logic:
// 1. Adding inventory items with cost and sale prices.
// 2. Enforcing profitability checks before an item can be "sold".
// 3. Tracking the total profit generated by the contract.
// This allows for a clear, isolated test of the profitability aspect of inventory management.

// A simple representation of an inventory item.
#[derive(Debug, PartialEq, Clone)]
struct InventoryItem {
    id: u64,
    cost: u64,
    sale_price: u64,
    is_sold: bool,
}

impl InventoryItem {
    fn new(id: u64, cost: u64, sale_price: u64) -> Self {
        Self { id, cost, sale_price, is_sold: false }
    }

    // Calculates the profit for this item if it were sold.
    // Returns 0 if not sold, or if sale_price <= cost (though the contract aims to prevent the latter).
    fn profit(&self) -> i64 {
        if self.is_sold {
            (self.sale_price as i64) - (self.cost as i64)
        } else {
            0
        }
    }
}

// A simplified model of a Direct Inventory Contract.
// This contract manages a collection of inventory items and enforces that items
// can only be 'sold' if the sale is strictly profitable (sale_price > cost).
#[derive(Debug, PartialEq, Default)]
struct DirectInventoryContract {
    inventory: Vec<InventoryItem>,
    total_profit: i64,
}

impl DirectInventoryContract {
    fn new() -> Self {
        Self::default()
    }

    // Adds a new item to the contract's inventory.
    fn add_item(&mut self, item: InventoryItem) {
        self.inventory.push(item);
    }

    // Attempts to "sell" an item by its ID.
    // This method enforces the profitability constraint: an item can only be sold
    // if its sale_price is strictly greater than its cost.
    // It also checks if the item exists and hasn't been sold already.
    fn sell_item_if_profitable(&mut self, item_id: u64) -> Result<(), String> {
        if let Some(item) = self.inventory.iter_mut().find(|i| i.id == item_id) {
            if item.is_sold {
                return Err(format!("Item {} already sold", item_id));
            }
            if item.sale_price <= item.cost {
                return Err(format!("Item {} cannot be sold profitably (cost: {}, price: {})", item_id, item.cost, item.sale_price));
            }
            item.is_sold = true;
            self.total_profit += item.profit();
            Ok(())
        } else {
            Err(format!("Item {} not found", item_id))
        }
    }

    // Returns the cumulative profit generated by all sold items in the contract.
    fn get_total_profit(&self) -> i64 {
        self.total_profit
    }
}

#[test]
fn test_end_to_end_profitable_inventory_contract_lifecycle() {
    // 1. Setup: Initialize a new Direct Inventory Contract.
    let mut contract = DirectInventoryContract::new();

    // 2. Add various inventory items, including profitable, non-profitable, and break-even ones.
    let item1 = InventoryItem::new(101, 100, 150); // Profitable: +50
    let item2 = InventoryItem::new(102, 200, 180); // Not profitable: -20
    let item3 = InventoryItem::new(103, 50, 75);   // Profitable: +25
    let item4 = InventoryItem::new(104, 100, 100); // Break-even: 0
    let item5 = InventoryItem::new(105, 300, 400); // Profitable: +100

    contract.add_item(item1.clone());
    contract.add_item(item2.clone());
    contract.add_item(item3.clone());
    contract.add_item(item4.clone());
    contract.add_item(item5.clone());

    // Initial state: No items sold, total profit should be 0.
    assert_eq!(contract.get_total_profit(), 0);

    // 3. Simulate selling profitable items and verify profit accumulation.
    // Sell item 1: Expected profit +50
    assert!(contract.sell_item_if_profitable(item1.id).is_ok());
    assert_eq!(contract.get_total_profit(), 50);

    // Sell item 3: Expected profit +25
    assert!(contract.sell_item_if_profitable(item3.id).is_ok());
    assert_eq!(contract.get_total_profit(), 75); // 50 + 25

    // Sell item 5: Expected profit +100
    assert!(contract.sell_item_if_profitable(item5.id).is_ok());
    assert_eq!(contract.get_total_profit(), 175); // 75 + 100

    // 4. Attempt to sell a non-profitable item (item2).
    // The contract should prevent this sale, and total profit should remain unchanged.
    let result_non_profitable = contract.sell_item_if_profitable(item2.id);
    assert!(result_non_profitable.is_err());
    assert!(result_non_profitable.unwrap_err().contains("cannot be sold profitably"));
    assert_eq!(contract.get_total_profit(), 175); // Profit should not change

    // 5. Attempt to sell a break-even item (item4).
    // The contract should prevent this sale as it's not strictly profitable.
    let result_break_even = contract.sell_item_if_profitable(item4.id);
    assert!(result_break_even.is_err());
    assert!(result_break_even.unwrap_err().contains("cannot be sold profitably"));
    assert_eq!(contract.get_total_profit(), 175); // Profit should not change

    // 6. Attempt to sell an already sold item (item1).
    // The contract should prevent re-selling.
    let result_already_sold = contract.sell_item_if_profitable(item1.id);
    assert!(result_already_sold.is_err());
    assert!(result_already_sold.unwrap_err().contains("already sold"));
    assert_eq!(contract.get_total_profit(), 175); // Profit should not change

    // 7. Attempt to sell a non-existent item (ID 999).
    // The contract should report that the item was not found.
    let result_not_found = contract.sell_item_if_profitable(999);
    assert!(result_not_found.is_err());
    assert!(result_not_found.unwrap_err().contains("not found"));
    assert_eq!(contract.get_total_profit(), 175); // Profit should not change
}
    