from __future__ import annotations

import json
import re
import sys
from pathlib import Path


SERVICE_NAMES = [
    "agent-bounties-api",
    "agent-bounties-mcp",
    "agent-bounties-base-indexer",
]


def fail(message: str) -> None:
    raise SystemExit(message)


def section(text: str, heading: str) -> str:
    marker = f"\n{heading}:\n"
    start = f"{text}\n".find(marker)
    if start == -1:
        if text.startswith(f"{heading}:\n"):
            start = -1
        else:
            fail(f"render.yaml missing {heading}: section")
    start += len(marker)
    next_top_level = re.search(r"\n[A-Za-z][A-Za-z0-9_-]*:\n", text[start:])
    if next_top_level:
        return text[start : start + next_top_level.start()]
    return text[start:]


def named_block(text: str, name: str) -> str:
    for match in re.finditer(r"(?ms)^  - type: .+?(?=^  - type: |\Z)", text):
        block = match.group(0)
        if f"name: {name}" in block:
            return block
    fail(f"render.yaml missing service block for {name}")


def env_entry(block: str, key: str) -> str:
    match = re.search(
        rf"(?ms)^      - key: {re.escape(key)}\n(?P<body>(?:        .+\n?)+)",
        block,
    )
    if not match:
        fail(f"service block missing env var {key}")
    body = match.group("body")
    next_key = re.search(r"^      - ", body, re.MULTILINE)
    return body[: next_key.start()] if next_key else body


def require_env_value(block: str, key: str, value: str) -> None:
    body = env_entry(block, key)
    if not re.search(rf"^\s+value: {re.escape(value)}\s*$", body, re.MULTILINE):
        fail(f"{key} must have value {value}")


def require_env_sync_false(block: str, key: str) -> None:
    body = env_entry(block, key)
    if not re.search(r"^\s+sync: false\s*$", body, re.MULTILINE):
        fail(f"{key} must be Dashboard-provided with sync: false")


def require_database_ref(block: str) -> None:
    body = env_entry(block, "DATABASE_URL")
    required = [
        "fromDatabase:",
        "name: agent-bounties-postgres",
        "property: connectionString",
    ]
    for item in required:
        if item not in body:
            fail(f"DATABASE_URL must use Render database reference {item}")


def env_group_block(text: str, name: str) -> str:
    groups = section(text, "envVarGroups")
    start = groups.find(f"  - name: {name}\n")
    if start == -1:
        fail(f"missing env var group {name}")
    end_match = re.search(r"^  - name: ", groups[start + 1 :], re.MULTILINE)
    return groups[start : start + 1 + end_match.start()] if end_match else groups[start:]


def require_group(text: str, name: str, keys: list[str]) -> str:
    group = env_group_block(text, name)
    for key in keys:
        if f"key: {key}" not in group:
            fail(f"env var group {name} missing {key}")
    if "STRIPE_SECRET_KEY" in keys and "sync: false" not in group:
        fail("Stripe secrets must be Dashboard-provided")
    if "OPERATOR_API_TOKEN" in keys and "generateValue: true" not in group:
        fail("OPERATOR_API_TOKEN must be generated by Render")
    return group


def require_address(value: object, label: str) -> str:
    if not isinstance(value, str) or not re.fullmatch(r"0x[0-9a-fA-F]{40}", value):
        fail(f"deployment manifest {label} must be an EVM address")
    return value


def load_mainnet_deployment(repo_root: Path) -> dict[str, object]:
    path = repo_root / "deployments" / "base-mainnet.json"
    if not path.exists():
        fail("missing deployments/base-mainnet.json")
    try:
        deployment = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"invalid Base mainnet deployment manifest: {error}")

    if deployment.get("schema_version") != 2:
        fail("Base mainnet deployment schema_version must be 2")
    if deployment.get("protocol_version") != "agent-bounties/autonomous-v1":
        fail("Base mainnet deployment must use autonomous-v1")
    if deployment.get("network") != "base-mainnet" or deployment.get("chain_id") != 8453:
        fail("Base mainnet deployment must target chain 8453")
    if deployment.get("rpc_url") != "https://mainnet.base.org":
        fail("Base mainnet deployment must use the official bootstrap RPC URL")
    require_address(deployment.get("native_usdc"), "native_usdc")

    status = deployment.get("status")
    if status not in {"pending_external_review_and_deployment", "active"}:
        fail("Base mainnet autonomous deployment status is invalid")
    factory = deployment.get("factory")
    if not isinstance(factory, dict):
        fail("Base mainnet deployment must contain factory metadata")
    if factory.get("source") != "contracts/base-escrow/src/AgentBountyFactory.sol:AgentBountyFactory":
        fail("deployment factory source does not identify the autonomous factory")
    constructor_args = factory.get("constructor_args")
    if not isinstance(constructor_args, dict) or constructor_args.get("settlement_token") != deployment.get("native_usdc"):
        fail("autonomous factory constructor must use Base native USDC")
    if status == "active":
        require_address(factory.get("contract"), "factory.contract")
        require_address(factory.get("implementation"), "factory.implementation")
        require_address(factory.get("deployer"), "factory.deployer")
        transaction = factory.get("deployment_transaction")
        if not isinstance(transaction, str) or not re.fullmatch(r"0x[0-9a-fA-F]{64}", transaction):
            fail("factory deployment_transaction must be a transaction hash")
        for key in ("runtime_code_hash", "implementation_runtime_code_hash"):
            value = factory.get(key)
            if not isinstance(value, str) or not re.fullmatch(r"0x[0-9a-fA-F]{64}", value):
                fail(f"factory.{key} must be a bytes32 hash")
        if not isinstance(factory.get("deployment_block"), int) or factory["deployment_block"] <= 0:
            fail("factory.deployment_block must be positive")

    policy = deployment.get("policy")
    if not isinstance(policy, dict):
        fail("deployment manifest must contain autonomous policy metadata")
    if policy.get("operator_settlement_signer") is not False:
        fail("autonomous protocol cannot configure an operator settlement signer")
    if policy.get("hosted_paid_state_requires_confirmed_bounty_settled_event") is not True:
        fail("hosted paid state must require confirmed BountySettled evidence")

    return deployment


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    deployment = load_mainnet_deployment(repo_root)
    rpc_url = str(deployment["rpc_url"])
    factory = deployment["factory"]
    assert isinstance(factory, dict)
    active = deployment["status"] == "active"

    blueprint = repo_root / "render.yaml"
    if not blueprint.exists():
        fail("missing render.yaml")
    text = blueprint.read_text(encoding="utf-8")
    if "\t" in text:
        fail("render.yaml must not contain tabs")
    for secret_marker in ("sk_live_", "sk_test_", "whsec_", "PRIVATE KEY"):
        if secret_marker in text:
            fail(f"render.yaml must not contain secret marker {secret_marker}")

    require_group(text, "agent-bounties-operator", ["OPERATOR_API_TOKEN"])
    require_group(
        text,
        "agent-bounties-stripe",
        [
            "STRIPE_SECRET_KEY",
            "STRIPE_WEBHOOK_SECRET",
            "STRIPE_PAYMENT_METHOD_CONFIGURATION",
        ],
    )
    base_group = require_group(
        text,
        "agent-bounties-base",
        [
            "BASE_SEPOLIA_RPC_URL",
            "BASE_MAINNET_RPC_URL",
            "BASE_SEPOLIA_USDC_TOKEN",
            "BASE_MAINNET_USDC_TOKEN",
            "BASE_SEPOLIA_BOUNTY_FACTORY",
            "BASE_SEPOLIA_BOUNTY_IMPLEMENTATION",
            "BASE_MAINNET_BOUNTY_FACTORY",
            "BASE_MAINNET_BOUNTY_IMPLEMENTATION",
        ],
    )
    require_env_sync_false(base_group, "BASE_SEPOLIA_RPC_URL")
    require_env_sync_false(base_group, "BASE_SEPOLIA_BOUNTY_FACTORY")
    require_env_sync_false(base_group, "BASE_SEPOLIA_BOUNTY_IMPLEMENTATION")
    require_env_value(base_group, "BASE_MAINNET_RPC_URL", rpc_url)
    require_env_value(base_group, "BASE_MAINNET_USDC_TOKEN", str(deployment["native_usdc"]))
    if active:
        require_env_value(base_group, "BASE_MAINNET_BOUNTY_FACTORY", str(factory["contract"]))
        require_env_value(base_group, "BASE_MAINNET_BOUNTY_IMPLEMENTATION", str(factory["implementation"]))
    else:
        require_env_sync_false(base_group, "BASE_MAINNET_BOUNTY_FACTORY")
        require_env_sync_false(base_group, "BASE_MAINNET_BOUNTY_IMPLEMENTATION")

    services = section(text, "services")
    for service_name in SERVICE_NAMES:
        block = named_block(services, service_name)
        if "runtime: docker" not in block:
            fail(f"{service_name} must use runtime: docker")
        if "dockerfilePath: ./Dockerfile" not in block:
            fail(f"{service_name} must build from the root Dockerfile")
        if "dockerContext: ." not in block:
            fail(f"{service_name} must build from the repo root context")
        if "autoDeployTrigger: commit" not in block:
            fail(f"{service_name} must deploy each reviewed main commit")
        require_database_ref(block)

    api = named_block(services, "agent-bounties-api")
    require_env_value(api, "APP_PACKAGE", "api")
    require_env_value(api, "APP_BINARY", "api")
    require_env_value(api, "ENABLE_STRIPE_LIVE_EXECUTION", '"false"')
    require_env_value(api, "ENABLE_STRIPE_PUBLIC_CHECKOUT", '"false"')
    require_env_value(api, "ENABLE_BASE_TX_BROADCAST", '"false"')
    if "healthCheckPath: /health" not in api:
        fail("API service must use /health")

    mcp = named_block(services, "agent-bounties-mcp")
    require_env_value(mcp, "APP_PACKAGE", "mcp-server")
    require_env_value(mcp, "APP_BINARY", "mcp-server")
    require_env_value(mcp, "ENABLE_STRIPE_LIVE_EXECUTION", '"false"')
    require_env_value(mcp, "ENABLE_STRIPE_PUBLIC_CHECKOUT", '"false"')
    require_env_value(mcp, "ENABLE_BASE_TX_BROADCAST", '"false"')
    if "healthCheckPath: /health" not in mcp:
        fail("MCP service must use /health")

    worker = named_block(services, "agent-bounties-base-indexer")
    if "type: worker" not in worker:
        fail("Base indexer must be a worker service")
    require_env_value(worker, "APP_PACKAGE", "worker")
    require_env_value(worker, "APP_BINARY", "worker")
    require_env_value(worker, "BASE_INDEXER_NETWORK", "base-mainnet")
    require_env_value(worker, "BASE_INDEXER_PROTOCOL", "autonomous-v1")
    require_env_value(worker, "BASE_INDEXER_RPC_URL", rpc_url)
    if active:
        require_env_value(worker, "BASE_INDEXER_FACTORY_CONTRACT", factory["contract"])
        require_env_value(worker, "BASE_INDEXER_START_BLOCK", f'"{factory["deployment_block"]}"')
    else:
        require_env_sync_false(worker, "BASE_INDEXER_START_BLOCK")

    env_example = (repo_root / ".env.example").read_text(encoding="utf-8")
    required_env_lines = [
        "ENABLE_BASE_TX_BROADCAST=false",
        f"BASE_MAINNET_RPC_URL={rpc_url}",
        f"BASE_MAINNET_USDC_TOKEN={deployment['native_usdc']}",
        "BASE_MAINNET_BOUNTY_FACTORY=",
        "BASE_MAINNET_BOUNTY_IMPLEMENTATION=",
        "BASE_INDEXER_NETWORK=base-mainnet",
        "BASE_INDEXER_PROTOCOL=autonomous-v1",
        f"BASE_INDEXER_RPC_URL={rpc_url}",
        "BASE_INDEXER_START_BLOCK=",
    ]
    env_lines = set(env_example.splitlines())
    for required in required_env_lines:
        if required not in env_lines:
            fail(f".env.example missing deployment coordinate {required}")

    database = section(text, "databases")
    for required in [
        "name: agent-bounties-postgres",
        "databaseName: agent_bounties",
        "user: agent_bounties",
        "postgresMajorVersion: \"16\"",
        "ipAllowList: []",
    ]:
        if required not in database:
            fail(f"database section missing {required}")

    print("render blueprint check ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
