from __future__ import annotations

import re
import sys
from pathlib import Path


SERVICE_NAMES = [
    "agent-bounties-api",
    "agent-bounties-mcp",
    "agent-bounties-base-indexer",
]


def fail(message: str) -> None:
    raise SystemExit(message)


def section(text: str, heading: str) -> str:
    marker = f"\n{heading}:\n"
    start = f"{text}\n".find(marker)
    if start == -1:
        if text.startswith(f"{heading}:\n"):
            start = -1
        else:
            fail(f"render.yaml missing {heading}: section")
    start += len(marker)
    next_top_level = re.search(r"\n[A-Za-z][A-Za-z0-9_-]*:\n", text[start:])
    if next_top_level:
        return text[start : start + next_top_level.start()]
    return text[start:]


def named_block(text: str, name: str) -> str:
    for match in re.finditer(r"(?ms)^  - type: .+?(?=^  - type: |\Z)", text):
        block = match.group(0)
        if f"name: {name}" in block:
            return block
    fail(f"render.yaml missing service block for {name}")


def env_entry(block: str, key: str) -> str:
    match = re.search(
        rf"(?ms)^      - key: {re.escape(key)}\n(?P<body>(?:        .+\n?)+)",
        block,
    )
    if not match:
        fail(f"service block missing env var {key}")
    body = match.group("body")
    next_key = re.search(r"^      - ", body, re.MULTILINE)
    return body[: next_key.start()] if next_key else body


def require_env_value(block: str, key: str, value: str) -> None:
    body = env_entry(block, key)
    if not re.search(rf"^\s+value: {re.escape(value)}\s*$", body, re.MULTILINE):
        fail(f"{key} must have value {value}")


def require_env_sync_false(block: str, key: str) -> None:
    body = env_entry(block, key)
    if not re.search(r"^\s+sync: false\s*$", body, re.MULTILINE):
        fail(f"{key} must be Dashboard-provided with sync: false")


def require_database_ref(block: str) -> None:
    body = env_entry(block, "DATABASE_URL")
    required = [
        "fromDatabase:",
        "name: agent-bounties-postgres",
        "property: connectionString",
    ]
    for item in required:
        if item not in body:
            fail(f"DATABASE_URL must use Render database reference {item}")


def require_group(text: str, name: str, keys: list[str]) -> None:
    groups = section(text, "envVarGroups")
    start = groups.find(f"  - name: {name}\n")
    if start == -1:
        fail(f"missing env var group {name}")
    end_match = re.search(r"^  - name: ", groups[start + 1 :], re.MULTILINE)
    group = groups[start : start + 1 + end_match.start()] if end_match else groups[start:]
    for key in keys:
        if f"key: {key}" not in group:
            fail(f"env var group {name} missing {key}")
    if "STRIPE_SECRET_KEY" in keys and "sync: false" not in group:
        fail("Stripe secrets must be Dashboard-provided")
    if "OPERATOR_API_TOKEN" in keys and "generateValue: true" not in group:
        fail("OPERATOR_API_TOKEN must be generated by Render")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    blueprint = repo_root / "render.yaml"
    if not blueprint.exists():
        fail("missing render.yaml")
    text = blueprint.read_text(encoding="utf-8")
    if "\t" in text:
        fail("render.yaml must not contain tabs")
    for secret_marker in ("sk_live_", "sk_test_", "whsec_", "PRIVATE KEY"):
        if secret_marker in text:
            fail(f"render.yaml must not contain secret marker {secret_marker}")

    require_group(text, "agent-bounties-operator", ["OPERATOR_API_TOKEN"])
    require_group(
        text,
        "agent-bounties-stripe",
        [
            "STRIPE_SECRET_KEY",
            "STRIPE_WEBHOOK_SECRET",
            "STRIPE_PAYMENT_METHOD_CONFIGURATION",
        ],
    )
    require_group(
        text,
        "agent-bounties-base",
        [
            "BASE_SEPOLIA_RPC_URL",
            "BASE_MAINNET_RPC_URL",
            "BASE_SEPOLIA_USDC_TOKEN",
            "BASE_MAINNET_USDC_TOKEN",
            "BASE_SEPOLIA_ESCROW_CONTRACT",
            "BASE_MAINNET_ESCROW_CONTRACT",
            "BASE_SETTLEMENT_SIGNER",
            "BASE_PLATFORM_FEE_WALLET",
        ],
    )

    services = section(text, "services")
    for service_name in SERVICE_NAMES:
        block = named_block(services, service_name)
        if "runtime: docker" not in block:
            fail(f"{service_name} must use runtime: docker")
        if "dockerfilePath: ./Dockerfile" not in block:
            fail(f"{service_name} must build from the root Dockerfile")
        if "dockerContext: ." not in block:
            fail(f"{service_name} must build from the repo root context")
        if "autoDeployTrigger: checksPass" not in block:
            fail(f"{service_name} must deploy only after checks pass")
        require_database_ref(block)

    api = named_block(services, "agent-bounties-api")
    require_env_value(api, "APP_PACKAGE", "api")
    require_env_value(api, "APP_BINARY", "api")
    require_env_value(api, "ENABLE_STRIPE_LIVE_EXECUTION", '"false"')
    require_env_value(api, "ENABLE_STRIPE_PUBLIC_CHECKOUT", '"false"')
    require_env_value(api, "ENABLE_BASE_TX_BROADCAST", '"false"')
    if "healthCheckPath: /health" not in api:
        fail("API service must use /health")

    mcp = named_block(services, "agent-bounties-mcp")
    require_env_value(mcp, "APP_PACKAGE", "mcp-server")
    require_env_value(mcp, "APP_BINARY", "mcp-server")
    require_env_value(mcp, "ENABLE_STRIPE_LIVE_EXECUTION", '"false"')
    require_env_value(mcp, "ENABLE_STRIPE_PUBLIC_CHECKOUT", '"false"')
    require_env_value(mcp, "ENABLE_BASE_TX_BROADCAST", '"false"')
    if "healthCheckPath: /health" not in mcp:
        fail("MCP service must use /health")

    worker = named_block(services, "agent-bounties-base-indexer")
    if "type: worker" not in worker:
        fail("Base indexer must be a worker service")
    require_env_value(worker, "APP_PACKAGE", "worker")
    require_env_value(worker, "APP_BINARY", "worker")
    require_env_value(worker, "BASE_INDEXER_NETWORK", "base-sepolia")
    require_env_sync_false(worker, "BASE_INDEXER_RPC_URL")
    require_env_sync_false(worker, "BASE_INDEXER_ESCROW_CONTRACT")
    require_env_sync_false(worker, "BASE_INDEXER_START_BLOCK")

    database = section(text, "databases")
    for required in [
        "name: agent-bounties-postgres",
        "databaseName: agent_bounties",
        "user: agent_bounties",
        "postgresMajorVersion: \"16\"",
        "ipAllowList: []",
    ]:
        if required not in database:
            fail(f"database section missing {required}")

    print("render blueprint check ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
